# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: vivian fang
email: vivian@eecs.berkeley.edu
description: EECS student @ UC Berkeley.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vivi.sh" # the base hostname & protocol for your site
github_username:  vivi

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

collections:
  technical:
    output: true
    permalink: /blog/technical/:path
  school:
    output: true
    permalink: /blog/school/:path
  food:
    output: true
    permalink: /blog/food/:path
  misc:
    output: true
    permalink: /blog/misc/:path
  notes:
    output: true
    permalink: /notes/:path

defaults:
  -
    scope:
      type: technical
      path: ""
    values:
      layout: "post"
  -
    scope:
      type: school
      path: ""
    values:
      layout: "post"
  -
    scope:
      type: food
      path: ""
    values:
      layout: "post"
  -
    scope:
      type: misc
      path: ""
    values:
      layout: "post"
